platform:ios,'6.0'

inhibit_all_warnings!

pod 'Masonry'
pod 'AFNetworking'
pod 'pop'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'TPKeyboardAvoiding'
pod 'ReactiveCocoa'
pod 'Masonry'
pod 'RRToolKit', :git => 'https://github.com/ringlong/RRToolKit', :branch => 'master'
pod 'IQKeyboardManager'
pod 'FLEX'

